/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Composable': RouteRecordInfo<'/Composable', '/Composable', Record<never, never>, Record<never, never>>,
    '/Custom': RouteRecordInfo<'/Custom', '/Custom', Record<never, never>, Record<never, never>>,
    '/ExerciseOne': RouteRecordInfo<'/ExerciseOne', '/ExerciseOne', Record<never, never>, Record<never, never>>,
    '/pageOne': RouteRecordInfo<'/pageOne', '/pageOne', Record<never, never>, Record<never, never>>,
    '/pageThree': RouteRecordInfo<'/pageThree', '/pageThree', Record<never, never>, Record<never, never>>,
    '/pageTwo': RouteRecordInfo<'/pageTwo', '/pageTwo', Record<never, never>, Record<never, never>>,
  }
}
