/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    BarChart: typeof import('./src/components/BarChart.vue')['default']
    DonutChart: typeof import('./src/components/DonutChart.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LineChart: typeof import('./src/components/LineChart.vue')['default']
    PieChart: typeof import('./src/components/PieChart.vue')['default']
    RadarChart: typeof import('./src/components/RadarChart.vue')['default']
  }
}
